### ISSUE TITLE
공통 코드 컨벤션 작성

### ISSUE THREAD

**Issue by crtEvent** [Flytrap-Ware/RSS-Reader#12]
## **☑️ 진행할 작업**
- 공통으로 작성할 코드 컨벤션을 결정하고 작성한다

## **📝TODO**
- [x] exception 처리 체계
- [x] 테스트 방식
- [x] configuration
- [x] property 관리 방식
- [x] 주석 컨벤션
- [x] 패키지 구조
- [x] API docs - swagger, rest docs
