### ISSUE TITLE
Member API 구현

### ISSUE THREAD

**Issue by new-pow** [Flytrap-Ware/RSS-Reader#16]
## **☑️ 진행할 작업**
- `global` 패키지 공통 코드 구현 
- Member API 구현

## **📝TODO**
- [x] Member 구현
    - [x] member repository, entity 구현
- [x] Github Oauth 로그인을 구현한다.
- [x] 로그아웃을 구현한다.
- [x] 회원 아이디로 회원을 검색할 수 있다.
- [x] oauth앱만들기
- [x] 단위 테스트 하기
- [x] 통합테스트 후 디버깅
- [x] #22

**Comment by new-pow** [comment]
## 논의할 사항
- [ ] Global session vs Local session

**Comment by new-pow** [comment]
## Oauth 시퀀스 다이어그램

```mermaid

sequenceDiagram
  participant Client
  participant Server

  Client ->> Server: 사용자에게 GitHub OAuth 인증 요청
  Server -->> Client: 사용자를 GitHub OAuth 인증 페이지로 리디렉션
  Client ->> GitHubOa
  uth: 사용자의 인증 코드 요청
  GitHubOauth -->> Client: 사용자의 인증 코드를 call back url로 전달
  Client ->> Server: 사용자의 인증 코드 전달
  Server ->> GitHubOauth: 사용자의 인증 코드를 사용하여 액세스 토큰 요청
  GitHubOauth ->> Server: 액세스 토큰 전달
  Server ->> GitHubOauth: 액세스 토큰을 사용하여 사용자 정보 요청
  GitHubOauth ->> Server: 사용자 정보 반환
  Server ->> Server: 회원가입 로직 수행

```
