### ISSUE TITLE
Member API 통합테스트 후 디버깅

### ISSUE THREAD

**Issue by new-pow** [Flytrap-Ware/RSS-Reader#27]
## **☑️ 진행할 작업**
- 구현한 Member API를 통합테스트하고 디버깅하였습니다.

## **📝TODO**
- [x] 이메일 반환이 안되었던 점 해결
- [x] `ApplicationResponse` 생성자 추가하여 컨트롤러 반환 못하는 에러 해결
- [x] Github API호출시 반환 매핑 수정

### Ref.
- #16

**Comment by crtEvent** [comment]
@new-pow 이린이 오늘의 MVP였습니다
